# Generated by Django 4.0.4 on 2022-05-16 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 12, 33, 14, 165702)),
        ),
    ]
