# Generated by Django 4.0.4 on 2022-05-17 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_create_time_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 9, 32, 17, 179446, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
